# **UFC _ Predictions**
Machine Learning model to predict the winner.
Make sure cell blocks are compiled and run sequentially

In [ ]:
!pip install feature_engine


In [ ]:
import numpy as np
import pandas as pd
import csv
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import make_pipeline
from feature_engine import imputation as mdi
from feature_engine import encoding as ce
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn import metrics


#matplotlib inline
with open('data.csv') as f:
    df = pd.read_csv(f)
f.close()
df.info()
df.head()

In [ ]:
with open('data.csv', newline='') as f:
  reader = csv.reader(f)
  row1 = next(reader)  # gets the first line
  # now do something here
  print(row1)
  # if first row is the header, then you can do one more next() to get the next row:
  # row2 = next(f)

In [3]:
#change winner (red/blue) to 1 or 0
df['Winner'] = df['Winner'].replace(['Red'],'0')
df['Winner'] = df['Winner'].replace(['Blue'],'1')
df['Winner'] = df['Winner'].replace(['Draw'],'2')
df['Winner'] = pd.to_numeric(df["Winner"])

In [ ]:
#feature variability
for col in df.columns:
    print(col, df[col].nunique(), len(df))


Drop unecessary columns

In [4]:
df.drop(['R_fighter'], axis=1, inplace=True)
df.drop(['B_fighter'], axis=1, inplace=True)
df.drop(['Referee'], axis=1, inplace=True)
df.drop(['location'], axis=1, inplace=True)
df.drop(['date'], axis=1, inplace=True)
df.drop(['title_bout'], axis=1, inplace=True)

In [ ]:
for var in df.columns:
    print(var, '\n', df[var].value_counts()/len(df))


Missing Values

In [ ]:
for var in df.columns:
    if df[var].isnull().sum()/len(df) > 0:
        print(var, df[var].isnull().mean().round(3))
#df.drop('tenure_termed', axis=1, inplace=True)

Train and Test split

In [5]:
#training and test splitting
y = df['Winner']
X = df.drop('Winner', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Scatterplot

In [ ]:
sns.scatterplot(x='B_avg_CLINCH_att', y='R_avg_opp_CLINCH_landed', hue='Winner', data=df)

Imputations and data encoding on missing values

In [6]:
# impute categorical features with more than 5% missing values w/ a new category 'missing'
process_pipe = make_pipeline(
    mdi.CategoricalImputer(variables=['R_Stance', 'B_Stance'
                                              ], imputation_method='missing'),
                             

  mdi.ArbitraryNumberImputer(arbitrary_number = 30, variables=['R_age', 'B_age']),

# Imputing missing values for numerical feature 'days_since_review' with an arbitrary digit
    mdi.ArbitraryNumberImputer(arbitrary_number = 0.0, variables=['B_avg_BODY_att', 'B_avg_BODY_landed', 'B_avg_CLINCH_att', 'B_avg_CLINCH_landed', 'B_avg_DISTANCE_att', 'B_avg_DISTANCE_landed', 'B_Reach_cms', 'R_Reach_cms', 'B_avg_GROUND_att', 'B_avg_GROUND_landed', 'B_avg_HEAD_att', 'B_avg_HEAD_landed', 'B_avg_KD', 'B_avg_LEG_att', 'B_avg_LEG_landed', 'B_avg_PASS', 'B_avg_REV', 'B_avg_SIG_STR_att', 'B_avg_SIG_STR_landed', 'B_avg_SIG_STR_pct', 'B_avg_SUB_ATT', 'B_avg_TD_att', 'B_avg_TD_landed', 'B_avg_TD_pct', 'B_avg_TOTAL_STR_att', 'B_avg_TOTAL_STR_landed', 'B_avg_opp_BODY_att', 'B_avg_opp_BODY_landed', 'B_avg_opp_CLINCH_att', 'B_avg_opp_CLINCH_landed', 'B_avg_opp_DISTANCE_att', 'B_avg_opp_DISTANCE_landed', 'B_avg_opp_GROUND_att', 'B_avg_opp_GROUND_landed', 'B_avg_opp_HEAD_att', 'B_avg_opp_HEAD_landed', 'B_avg_opp_KD', 'B_avg_opp_LEG_att', 'B_avg_opp_LEG_landed', 'B_avg_opp_PASS', 'B_avg_opp_REV', 'B_avg_opp_SIG_STR_att', 'B_avg_opp_SIG_STR_landed', 'B_avg_opp_SIG_STR_pct', 'B_avg_opp_SUB_ATT', 'B_avg_opp_TD_att', 'B_avg_opp_TD_landed', 'B_avg_opp_TD_pct', 'B_avg_opp_TOTAL_STR_att', 'B_avg_opp_TOTAL_STR_landed',
                                                                  'B_total_time_fought(seconds)', 'R_avg_BODY_att', 'R_avg_BODY_landed', 'R_avg_CLINCH_att', 'R_avg_CLINCH_landed', 'R_avg_DISTANCE_att', 'R_avg_DISTANCE_landed', 'R_avg_GROUND_att', 'R_avg_GROUND_landed', 'R_avg_HEAD_att', 'R_avg_HEAD_landed', 'R_avg_KD', 'R_avg_LEG_att', 'R_avg_LEG_landed', 'R_avg_PASS', 'R_avg_REV', 'R_avg_SIG_STR_att', 'R_avg_SIG_STR_landed', 'R_avg_SIG_STR_pct', 'R_avg_SUB_ATT', 'R_avg_TD_att', 'R_avg_TD_landed', 'R_avg_TD_pct', 'R_avg_TOTAL_STR_att', 'R_avg_TOTAL_STR_landed', 
                                                                  'R_avg_opp_BODY_att', 'R_avg_opp_BODY_landed', 'R_avg_opp_CLINCH_att', 'R_avg_opp_CLINCH_landed', 'R_avg_opp_DISTANCE_att', 'R_avg_opp_DISTANCE_landed', 'R_avg_opp_GROUND_att', 'R_avg_opp_GROUND_landed', 'R_avg_opp_HEAD_att', 'R_avg_opp_HEAD_landed', 'R_avg_opp_KD', 'R_avg_opp_LEG_att', 'R_avg_opp_LEG_landed', 'R_avg_opp_PASS', 'R_avg_opp_REV', 'R_avg_opp_SIG_STR_att', 'R_avg_opp_SIG_STR_landed', 'R_avg_opp_SIG_STR_pct', 'R_avg_opp_SUB_ATT', 'R_avg_opp_TD_att', 'R_avg_opp_TD_landed', 'R_avg_opp_TD_pct', 'R_avg_opp_TOTAL_STR_att', 'R_avg_opp_TOTAL_STR_landed', 'R_total_time_fought(seconds)'
                                                                  ]),
    
# Target or Mean encoding for categorical features
    ce.OrdinalEncoder(encoding_method='ordered',
    variables=['weight_class', 'R_Stance', 'B_Stance'] 
))

In [ ]:
process_pipe.fit(X_train, y_train)
X_train_clean = process_pipe.transform(X_train)
X_test_clean = process_pipe.transform(X_test)



X_train_clean = X_train_clean.fillna(X_train_clean.mean())
X_test_clean = X_test_clean.fillna(X_test_clean.mean())

X_train_clean.head()

Machine Learning Training: **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

# all parameters not specified are set to their defaults
model = LogisticRegression(solver='liblinear')
model.fit(X_train_clean, y_train)


In [9]:
predictions = model.predict(X_test_clean)

score = model.score(X_test_clean, y_test)
score1 = model.score(X_train_clean, y_train)
print(score)

0.6958211856171039


Model Performance Visualisation

In [ ]:
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

plt.figure(figsize=(9,9))
sns.heatmap(cm, annot=True, fmt=".3f", linewidths=.5, square = True, cmap = 'Blues_r');
plt.ylabel('Actual label');
plt.xlabel('Predicted label');
all_sample_title = 'Accuracy Score: {0}'.format(score)
plt.title(all_sample_title, size = 15);

Naive Bayes model training and testing

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB 
cnb = ComplementNB()
bnb = BernoulliNB()
mnb = MultinomialNB()
gnb = GaussianNB()

y_pred = cnb.fit(X_train_clean, y_train).predict(X_test_clean)
print("Number of mislabeled points out of a total %d points : %d" % (X_test_clean.shape[0], (y_test != y_pred).sum()))
print(cnb.score(X_test_clean, y_test))


Number of mislabeled points out of a total 1029 points : 423
0.5889212827988338


**SVM Classifier**

In [ ]:
from sklearn import svm
modelSVM = svm.SVC()
modelSVM.fit(X_train_clean, y_train)
modelSVM.predict(X_test_clean)

scoreSVM = modelSVM.score(X_test_clean, y_test)
print(scoreSVM)

0.6919339164237124


**Neural Networks**

[Unbalanced resource api](https://imbalanced-learn.org/stable/user_guide.html)

In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X_train_clean, y_train)

y_pred1 = clf.predict(X_test_clean)
scoreN = clf.score(X_test_clean, y_test)
print(scoreN)

0.6919339164237124




**Evaluations of Models**

In [10]:
#evaluation of current model cross_validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
from sklearn.model_selection import KFold

lr_scores = cross_val_score(model, X_test_clean, y_test, cv=5)
print(lr_scores)

#validat method
#It allows specifying multiple metrics for evaluation.
#It returns a dict containing fit-times, score-times (and optionally training scores as well as fitted estimators) in addition to the test score.
scoring = ['precision_macro', 'recall_macro']
lr2_scores = cross_validate(model, X_test_clean, y_test, scoring=scoring)
sorted(lr2_scores.keys())
lr2_scores['test_recall_macro']

[0.65048544 0.63106796 0.61650485 0.67475728 0.63414634]


array([0.37872862, 0.37604204, 0.33982786, 0.3872457 , 0.35469881])

Testing kfold cross validation

In [ ]:
process_pipe.fit(X, y)
X_clean = process_pipe.transform(X)
X_clean.head()

#kfold
kf = KFold(n_splits=5)
for train, test in kf.split(X_clean):
  print("%s %s" % (train, test))

**Using the Model**
*   Input fighters name to pull from database
*   Model will predict who wins



In [ ]:
#check format
with open('ufc259.csv') as f:
    df1 = pd.read_csv(f)
f.close()
df1.info()
df1.head()

predictions_new = clf.predict(df1)

print(predictions_new)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Columns: 138 entries, weight_class to R_age
dtypes: float64(102), int64(36)
memory usage: 4.4 KB
[0 0 0 0]
